In [192]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.12


### Exercícios Sobre Módulos Python Para Análise de Dados

### Exercício 1

In [63]:
# Crie um array NumPy com 1.000.000 e uma lista com 1.000.000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import numpy as pd

lista = list(map(lambda x:x*2, range(100000)))
array = list(map(lambda x: x*2, np.array(range(0,100000))))

%time

CPU times: total: 0 ns
Wall time: 0 ns


### Exercício 2

In [75]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

import numpy as np
#crindo um array de 10 elementos.
array = np.array(range(0,10))
print(array)

#Alterando os indices do 5 ao 8 do array
array[5:8] = 0
print(array)


[0 1 2 3 4 0 0 0 8 9]


### Exercício 3

In [76]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
import numpy as pd

tresD = np.array([[[1,4,7],[3,5,2]],[[5,6,0],[7,4,1]],[[2,8,8],[0,3,6]]])

tresD[0]

array([[1, 4, 7],
       [3, 5, 2]])

### Exercício 4

In [93]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
print('*'*40)
#Elementos da terceira linha
print(array[2])
print('*'*40)
#todos os elementos da primeira e segunda linha 

print(array[:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
****************************************
[7 8 9]
****************************************
[[2 3]
 [5 6]]


### Exercício 5

In [101]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print(arr)
print('\n')
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]




array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [121]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
solucao = []
for x,y,z in zip(xarr,yarr,cond):
    print(x,y,z)
    if z == True:
        solucao.append(x)
    else:
        solucao.append(y)
print(solucao)    

#solução aplicada pela DSA

resultado = [(x if z else y) for x, y, z in zip(xarr, yarr, cond)]
resultado

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False
[1.1, 2.2, 1.3, 1.4, 2.5]


[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [189]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
import numpy as np
original= np.arange(10)
print(original)
np.save('array_original', original)

[0 1 2 3 4 5 6 7 8 9]


In [191]:
copia = np.load('array_original.npy')
print(copia)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [127]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

unicos = set(obj)
print(unicos) # retorna um dicionário

#Sulução da DSA
uniques = obj.unique() #Retorna uma lista
print(uniques)

{'c', 'b', 'a', 'd'}
['c' 'a' 'd' 'b']


### Exercício 9

In [132]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [152]:
#Vizualizando os nomes das colunas.
vizualizando = pd.read_json(url)
vizualizando[:2] 


url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   

                                   repository_url  \
0  https://api.github.com/repos/pandas-dev/pandas   
1  https://api.github.com/repos/pandas-dev/pandas   

                                          labels_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   

                                        comments_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   

                                          events_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   

                                          html_url          id  \
0  https://github.com/pandas-dev/pandas/pull/47558  1290800722   
1  https://github.com/pandas-dev/pandas/pull/47557  1290756094   

               node_id  number  \
0  PR_kwDOAA0YD846rTY_   47558   
1  PR_kwDOAA0YD846rJ9C   47557   

                                               title  ... closed_at  \
0                  TYP: misc return type annotations  ...       NaT   
1  ENH: RangeIndex._shallow_copy can return Range...  ...       NaT   

  author_association active_lock_reason  draft  \
0        CONTRIBUTOR                NaN    0.0   
1             MEMBER                NaN    0.0   

                                        pull_request  \
0  {'url': 'https://api.github.com/repos/pandas-d...   
1  {'url': 'https://api.github.com/repos/pandas-d...   

                                                body  \
0  After this most of the low hanging return anno...   
1  - [ ] closes #xxxx (Replace xxxx with the Gith...   

                                           reactions  \
0  {'url': 'https://api.github.com/repos/pandas-d...   
1  {'url': 'https://api.github.com/repos/pandas-d...   

                                        timeline_url performed_via_github_app  \
0  https://api.github.com/repos/pandas-dev/pandas...                      NaN   
1  https://api.github.com/repos/pandas-dev/pandas...                      NaN   

  state_reason  
0          NaN  
1          NaN  

[2 rows x 30 columns]

In [159]:
arq = resp.json()
df = pd.DataFrame(arq, columns=['id','url','number', 'title','author_association', 'state'])
df

id                                                url  number  \
0   1290756094  https://api.github.com/repos/pandas-dev/pandas...   47557   
1   1290675587  https://api.github.com/repos/pandas-dev/pandas...   47555   
2   1290039010  https://api.github.com/repos/pandas-dev/pandas...   47554   
3   1289521402  https://api.github.com/repos/pandas-dev/pandas...   47553   
4   1289422658  https://api.github.com/repos/pandas-dev/pandas...   47552   
5   1288978436  https://api.github.com/repos/pandas-dev/pandas...   47550   
6   1288852049  https://api.github.com/repos/pandas-dev/pandas...   47549   
7   1288550053  https://api.github.com/repos/pandas-dev/pandas...   47548   
8   1288404337  https://api.github.com/repos/pandas-dev/pandas...   47547   
9   1288365319  https://api.github.com/repos/pandas-dev/pandas...   47545   
10  1288364342  https://api.github.com/repos/pandas-dev/pandas...   47544   
11  1288341688  https://api.github.com/repos/pandas-dev/pandas...   47543   
12  1288282922  https://api.github.com/repos/pandas-dev/pandas...   47542   
13  1287979506  https://api.github.com/repos/pandas-dev/pandas...   47539   
14  1287772391  https://api.github.com/repos/pandas-dev/pandas...   47534   
15  1287674797  https://api.github.com/repos/pandas-dev/pandas...   47533   
16  1287579308  https://api.github.com/repos/pandas-dev/pandas...   47532   
17  1287459872  https://api.github.com/repos/pandas-dev/pandas...   47530   
18  1287291228  https://api.github.com/repos/pandas-dev/pandas...   47529   
19  1286987703  https://api.github.com/repos/pandas-dev/pandas...   47527   
20  1286963118  https://api.github.com/repos/pandas-dev/pandas...   47526   
21  1286943976  https://api.github.com/repos/pandas-dev/pandas...   47525   
22  1286591632  https://api.github.com/repos/pandas-dev/pandas...   47523   
23  1286532691  https://api.github.com/repos/pandas-dev/pandas...   47521   
24  1286074977  https://api.github.com/repos/pandas-dev/pandas...   47519   
25  1285953894  https://api.github.com/repos/pandas-dev/pandas...   47518   
26  1285075103  https://api.github.com/repos/pandas-dev/pandas...   47515   
27  1285051682  https://api.github.com/repos/pandas-dev/pandas...   47514   
28  1285007724  https://api.github.com/repos/pandas-dev/pandas...   47513   
29  1284929524  https://api.github.com/repos/pandas-dev/pandas...   47511   

                                                title author_association state  
0   ENH: RangeIndex._shallow_copy can return Range...             MEMBER  open  
1                    REF: share some constructor code             MEMBER  open  
2   BUG: Series with same index values, but in dif...        CONTRIBUTOR  open  
3   REF: Reduce duplicative methods between XML pa...        CONTRIBUTOR  open  
4   ENH/TST: Add BaseMethodsTests tests for ArrowE...             MEMBER  open  
5                           REGR: Ignore eval inplace             MEMBER  open  
6   BUG: incorrect result of applying iloc with slice               NONE  open  
7   TYP: level parameter of DataFrame.groupby has ...               NONE  open  
8   REGR: NotImplementedErorr: Prefix not defined ...             MEMBER  open  
9   BUG: datetime index name droped after date_ran...        CONTRIBUTOR  open  
10  BUG: decimal.Decimal treated as string in Data...               NONE  open  
11  API: Inconsistent use of `apply` arguments arg...             MEMBER  open  
12  Having the axis variable in the .apply functio...               NONE  open  
13  Update `to_gbq` wrapper method to contain `api...               NONE  open  
14  API: ExtensionArray._from_sequence_of_strings ...             MEMBER  open  
15  DOC: Add information about StyleFrame, to form...        CONTRIBUTOR  open  
16             WEB: Update to `jupyterlite==0.1.0b10`        CONTRIBUTOR  open  
17                 WEB: JupyterLite terminal too slow             MEMBER  open  
18  DOC: missed behavior explaination of sort=Fals...               NONE  open  
19  

### Exercício 10

In [174]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3

#Criando a conexão e a query 
queryC = '''
    CREATE TABLE exercicio (
    id INTEGER NOT NULL ,
    nome Varchar(40) NOT NULL,
    estado Varchar(20) NOT NULL,
    cidade Varchar(20) NOT NULL,
    pais Varchar(20) NOT NULL DEFAULT 'Brasil',
    PRIMARY KEY("id" AUTOINCREMENT)
);
    
'''

conexao = sqlite3.connect('exercicio.db')
conexao.execute(queryC)
conexao.commit()

In [175]:
dados = [(1, 'Marcos Guedes', 'São Paulo', 'Araras', 'Brasil'),
        (2,'Harry Potter', 'Acre','Rio branco','Brasil'),
        (3,'Flavia','Paraná', 'Londrina', 'Italia')]
queryI = "INSERT INTO exercicio VALUES(?,?, ?, ?, ?)"
conexao.executemany(queryI, dados)
conexao.commit()

In [183]:
import pandas as pd
cursor = conexao.execute('SELECT * FROM exercicio')
df = pd.DataFrame(list(cursor), columns = ['id','nome','estado','cidade','Pais'])
#Ajustando para uma melhor vizualização dos index como ID.
df.set_index('id') 


nome     estado      cidade    Pais
id                                              
1   Marcos Guedes  São Paulo      Araras  Brasil
2    Harry Potter       Acre  Rio branco  Brasil
3          Flavia     Paraná    Londrina  Italia

# Fim